-- OSNet 품종 분류 모델(dog_breeds.txt, 130품종) 라벨을 breeds 마스터에 시드.
-- code = main_v3.py 의 _load_breed_codes 와 동일 변환 (공백→_, 대문자).
-- → /pending 의 predicted_breed_code 가 breeds.code 와 매칭되어 등록 모달이 자동 prefill.
-- 기존 12행과 겹치는 코드(POMERANIAN/BEAGLE/CHIHUAHUA)는 on conflict 로 보존.
-- daily_g_per_kg: 크기등급 추정값 (소형 22 / 중형 18 / 대형 15).

insert into public.breeds (code, name_ko, name_en, daily_g_per_kg) values
  ('SHIBA_DOG', '시바견', 'Shiba Dog', 18),
  ('FRENCH_BULLDOG', '프렌치불독', 'French Bulldog', 18),
  ('SIBERIAN_HUSKY', '시베리안허스키', 'Siberian Husky', 15),
  ('MALAMUTE', '알래스칸맬러뮤트', 'Malamute', 15),
  ('POMERANIAN', '포메라니안', 'Pomeranian', 22),
  ('AIREDALE', '에어데일테리어', 'Airedale', 15),
  ('MINIATURE_POODLE', '미니어처푸들', 'Miniature Poodle', 22),
  ('AFFENPINSCHER', '아펜핀셔', 'Affenpinscher', 22),
  ('SCHIPPERKE', '스키퍼키', 'Schipperke', 22),
  ('AUSTRALIAN_TERRIER', '오스트레일리언테리어', 'Australian Terrier', 22),
  ('WELSH_SPRINGER_SPANIEL', '웰시스프링어스패니얼', 'Welsh Springer Spaniel', 18),
  ('CURLY_COATED_RETRIEVER', '컬리코티드리트리버', 'Curly Coated Retriever', 15),
  ('STAFFORDSHIRE_BULLTERRIER', '스태퍼드셔불테리어', 'Staffordshire Bullterrier', 18),
  ('NORWICH_TERRIER', '노리치테리어', 'Norwich Terrier', 22),
  ('TIBETAN_TERRIER', '티베탄테리어', 'Tibetan Terrier', 18),
  ('ENGLISH_SETTER', '잉글리시세터', 'English Setter', 15),
  ('NORFOLK_TERRIER', '노퍽테리어', 'Norfolk Terrier', 22),
  ('PEMBROKE', '펨브로크웰시코기', 'Pembroke', 18),
  ('TIBETAN_MASTIFF', '티베탄마스티프', 'Tibetan Mastiff', 15),
  ('BORDER_TERRIER', '보더테리어', 'Border Terrier', 22),
  ('GREAT_DANE', '그레이트데인', 'Great Dane', 15),
  ('SCOTCH_TERRIER', '스코티시테리어', 'Scotch Terrier', 22),
  ('FLAT_COATED_RETRIEVER', '플랫코티드리트리버', 'Flat Coated Retriever', 15),
  ('SALUKI', '살루키', 'Saluki', 15),
  ('IRISH_SETTER', '아이리시세터', 'Irish Setter', 15),
  ('BLENHEIM_SPANIEL', '블레넘스패니얼', 'Blenheim Spaniel', 22),
  ('IRISH_TERRIER', '아이리시테리어', 'Irish Terrier', 18),
  ('BLOODHOUND', '블러드하운드', 'Bloodhound', 15),
  ('REDBONE', '레드본쿤하운드', 'Redbone', 15),
  ('WEST_HIGHLAND_WHITE_TERRIER', '웨스트하이랜드화이트테리어', 'West Highland White Terrier', 22),
  ('BRABANCON_GRIFFO', '브뤼셀그리펀', 'Brabancon Griffo', 22),
  ('DHOLE', '돌(아시아들개)', 'Dhole', 18),
  ('KELPIE', '오스트레일리언켈피', 'Kelpie', 18),
  ('DOBERMAN', '도베르만', 'Doberman', 15),
  ('IBIZAN_HOUND', '이비전하운드', 'Ibizan Hound', 15),
  ('VIZSLA', '비즐라', 'Vizsla', 15),
  ('CAIRN', '케언테리어', 'Cairn', 22),
  ('GERMAN_SHEPHERD', '저먼셰퍼드', 'German Shepherd', 15),
  ('AFRICAN_HUNTING_DOG', '아프리카들개', 'African Hunting Dog', 15),
  ('DANDIE_DINMONT', '댄디딘몬트테리어', 'Dandie Dinmont', 22),
  ('SEALYHAM_TERRIER', '실리햄테리어', 'Sealyham Terrier', 22),
  ('GERMAN_SHORT_HAIRED_POINTER', '저먼쇼트헤어드포인터', 'German Short Haired Pointer', 15),
  ('BERNESE_MOUNTAIN_DOG', '버니즈마운틴독', 'Bernese Mountain Dog', 15),
  ('SAINT_BERNARD', '세인트버나드', 'Saint Bernard', 15),
  ('LEONBERG', '레온베르거', 'Leonberg', 15),
  ('BEDLINGTON_TERRIER', '베들링턴테리어', 'Bedlington Terrier', 22),
  ('NEWFOUNDLAND', '뉴펀들랜드', 'Newfoundland', 15),
  ('LHASA', '라사압소', 'Lhasa', 22),
  ('CHESAPEAKE_BAY_RETRIEVER', '체서피크베이리트리버', 'Chesapeake Bay Retriever', 15),
  ('LAKELAND_TERRIER', '레이클랜드테리어', 'Lakeland Terrier', 22),
  ('WALKER_HOUND', '트리잉워커쿤하운드', 'Walker Hound', 15),
  ('AMERICAN_STAFFORDSHIRE_TERRIER', '아메리칸스태퍼드셔테리어', 'American Staffordshire Terrier', 15),
  ('OTTERHOUND', '오터하운드', 'Otterhound', 15),
  ('SUSSEX_SPANIEL', '서식스스패니얼', 'Sussex Spaniel', 18),
  ('NORWEGIAN_ELKHOUND', '노르웨이언엘크하운드', 'Norwegian Elkhound', 18),
  ('BLUETICK', '블루틱쿤하운드', 'Bluetick', 15),
  ('DINGO', '딩고', 'Dingo', 18),
  ('IRISH_WATER_SPANIEL', '아이리시워터스패니얼', 'Irish Water Spaniel', 15),
  ('SAMOYED', '사모예드', 'Samoyed', 15),
  ('FILA_BRAZILIERO', '필라브라질레이로', 'Fila Braziliero', 15),
  ('STANDARD_SCHNAUZER', '스탠더드슈나우저', 'Standard Schnauzer', 18),
  ('MEXICAN_HAIRLESS', '멕시칸헤어리스독', 'Mexican Hairless', 18),
  ('ENTLEBUCHER', '엔틀레부허마운틴독', 'Entlebucher', 15),
  ('AFGHAN_HOUND', '아프간하운드', 'Afghan Hound', 15),
  ('KUVASZ', '쿠바스', 'Kuvasz', 15),
  ('ENGLISH_FOXHOUND', '잉글리시폭스하운드', 'English Foxhound', 15),
  ('KEESHOND', '키스혼드', 'Keeshond', 18),
  ('IRISH_WOLFHOUND', '아이리시울프하운드', 'Irish Wolfhound', 15),
  ('SCOTTISH_DEERHOUND', '스코티시디어하운드', 'Scottish Deerhound', 15),
  ('ROTTWEILER', '로트와일러', 'Rottweiler', 15),
  ('BLACK_AND_TAN_COONHOUND', '블랙앤탄쿤하운드', 'Black And Tan Coonhound', 15),
  ('GREAT_PYRENEES', '그레이트피레니즈', 'Great Pyrenees', 15),
  ('BOXER', '복서', 'Boxer', 15),
  ('WIRE_HAIRED_FOX_TERRIER', '와이어헤어드폭스테리어', 'Wire Haired Fox Terrier', 22),
  ('BORZOI', '보르조이', 'Borzoi', 15),
  ('GROENENDAEL', '그로넨달(벨지언셰퍼드)', 'Groenendael', 15),
  ('COLLIE', '콜리', 'Collie', 15),
  ('GORDON_SETTER', '고든세터', 'Gordon Setter', 15),
  ('KERRY_BLUE_TERRIER', '케리블루테리어', 'Kerry Blue Terrier', 18),
  ('BRIARD', '브리아드', 'Briard', 15),
  ('RHODESIAN_RIDGEBACK', '로디지안리지백', 'Rhodesian Ridgeback', 15),
  ('BOSTON_BULL', '보스턴테리어', 'Boston Bull', 22),
  ('BULL_MASTIFF', '불마스티프', 'Bull Mastiff', 15),
  ('SILKY_TERRIER', '실키테리어', 'Silky Terrier', 22),
  ('BRITTANY_SPANIEL', '브리타니스패니얼', 'Brittany Spaniel', 18),
  ('ESKIMO_DOG', '에스키모독', 'Eskimo Dog', 15),
  ('GIANT_SCHNAUZER', '자이언트슈나우저', 'Giant Schnauzer', 15),
  ('MALINOIS', '말리노이즈', 'Malinois', 15),
  ('BOUVIER_DES_FLANDRES', '부비에데플랑드르', 'Bouvier Des Flandres', 15),
  ('WHIPPET', '휘핏', 'Whippet', 18),
  ('APPENZELLER', '아펜젤러마운틴독', 'Appenzeller', 15),
  ('CHINESE_CRESTED_DOG', '차이니즈크레스티드독', 'Chinese Crested Dog', 22),
  ('MINIATURE_SCHNAUZER', '미니어처슈나우저', 'Miniature Schnauzer', 22),
  ('SOFT_COATED_WHEATEN_TERRIER', '소프트코티드휘튼테리어', 'Soft Coated Wheaten Terrier', 18),
  ('WEIMARANER', '바이마라너', 'Weimaraner', 15),
  ('CLUMBER', '클럼버스패니얼', 'Clumber', 15),
  ('GREATER_SWISS_MOUNTAIN_DOG', '그레이터스위스마운틴독', 'Greater Swiss Mountain Dog', 15),
  ('TOY_TERRIER', '토이테리어', 'Toy Terrier', 22),
  ('ITALIAN_GREYHOUND', '이탈리안그레이하운드', 'Italian Greyhound', 22),
  ('BASSET', '바셋하운드', 'Basset', 15),
  ('BASENJI', '바센지', 'Basenji', 22),
  ('AUSTRALIAN_SHEPHERD', '오스트레일리언셰퍼드', 'Australian Shepherd', 15),
  ('MALTESE_DOG', '몰티즈', 'Maltese Dog', 22),
  ('JAPANESE_SPANIEL', '재패니즈친', 'Japanese Spaniel', 22),
  ('CANE_CARSO', '카네코르소', 'Cane Carso', 15),
  ('JAPANESE_SPITZES', '재패니즈스피츠', 'Japanese Spitzes', 22),
  ('OLD_ENGLISH_SHEEPDOG', '올드잉글리시십독', 'Old English Sheepdog', 15),
  ('BLACK_SABLE', '블랙세이블', 'Black Sable', 18),
  ('BORDER_COLLIE', '보더콜리', 'Border Collie', 18),
  ('SHETLAND_SHEEPDOG', '셰틀랜드십독', 'Shetland Sheepdog', 22),
  ('ENGLISH_SPRINGER', '잉글리시스프링어스패니얼', 'English Springer', 18),
  ('BEAGLE', '비글', 'Beagle', 18),
  ('COCKER_SPANIEL', '코커스패니얼', 'Cocker Spaniel', 18),
  ('CARDIGAN', '카디건웰시코기', 'Cardigan', 18),
  ('TOY_POODLE', '토이푸들', 'Toy Poodle', 22),
  ('BICHON_FRISE', '비숑프리제', 'Bichon Frise', 22),
  ('STANDARD_POODLE', '스탠더드푸들', 'Standard Poodle', 15),
  ('KOMONDOR', '코몬도르', 'Komondor', 15),
  ('CHOW', '차우차우', 'Chow', 15),
  ('CHINESE_RURAL_DOG', '차이니즈루럴독', 'Chinese Rural Dog', 18),
  ('YORKSHIRE_TERRIER', '요크셔테리어', 'Yorkshire Terrier', 22),
  ('LABRADOR_RETRIEVER', '래브라도리트리버', 'Labrador Retriever', 15),
  ('SHIH_TZU', '시츄', 'Shih Tzu', 22),
  ('CHIHUAHUA', '치와와', 'Chihuahua', 22),
  ('PEKINESE', '페키니즈', 'Pekinese', 22),
  ('GOLDEN_RETRIEVER', '골든리트리버', 'Golden Retriever', 15),
  ('MINIATURE_PINSCHER', '미니어처핀셔', 'Miniature Pinscher', 22),
  ('TEDDY', '테디베어독', 'Teddy', 22),
  ('PUG', '퍼그', 'Pug', 22),
  ('PAPILLON', '파피용', 'Papillon', 22)
on conflict (code) do nothing;
