import type {
  AppAlert,
  Breed,
  Device,
  Dog,
  FeedingRecord,
} from "@/types";

export const breeds: Breed[] = [
  { code: "MALTESE", name_ko: "몰티즈", name_en: "Maltese", daily_g_per_kg: 22 },
  { code: "POODLE", name_ko: "푸들", name_en: "Poodle", daily_g_per_kg: 20 },
  { code: "POMERANIAN", name_ko: "포메라니안", name_en: "Pomeranian", daily_g_per_kg: 24 },
  { code: "BICHON", name_ko: "비숑프리제", name_en: "Bichon Frise", daily_g_per_kg: 21 },
  { code: "SHIHTZU", name_ko: "시츄", name_en: "Shih Tzu", daily_g_per_kg: 18 },
  { code: "MIXED", name_ko: "믹스견", name_en: "Mixed", daily_g_per_kg: 20 },
];

export const dogs: Dog[] = [
  {
    id: "dog-1",
    name: "1번 개체",
    breed_code: "MALTESE",
    breed_name_ko: "몰티즈",
    weight_kg: 3.2,
    status: "active",
    created_at: "2026-03-18T10:00:00Z",
    food_type: "소형견용 일반사료",
    recommended_g: 60,
    vet_note: "알레르기 없음. 체중 유지 중.",
  },
  {
    id: "dog-2",
    name: "2번 개체",
    breed_code: "POODLE",
    breed_name_ko: "푸들",
    weight_kg: 5.1,
    status: "active",
    created_at: "2026-03-15T10:00:00Z",
    food_type: "소형견용 일반사료",
    recommended_g: 75,
  },
  {
    id: "dog-3",
    name: "3번 개체",
    breed_code: "POMERANIAN",
    breed_name_ko: "포메라니안",
    weight_kg: 2.8,
    status: "active",
    created_at: "2026-03-12T10:00:00Z",
    food_type: "소형견용 일반사료",
    recommended_g: 50,
  },
  {
    id: "dog-4",
    name: "4번 개체",
    breed_code: "BICHON",
    breed_name_ko: "비숑프리제",
    weight_kg: 4.5,
    status: "active",
    created_at: "2026-03-10T10:00:00Z",
    food_type: "소형견용 일반사료",
    recommended_g: 55,
  },
  {
    id: "dog-5",
    name: "5번 개체",
    breed_code: "SHIHTZU",
    breed_name_ko: "시츄",
    weight_kg: 5.8,
    status: "active",
    created_at: "2026-03-08T10:00:00Z",
    food_type: "중형견용 일반사료",
    recommended_g: 55,
  },
  {
    id: "dog-6",
    name: "6번 개체",
    breed_code: "MIXED",
    breed_name_ko: "믹스견",
    weight_kg: 7.2,
    status: "active",
    created_at: "2026-03-05T10:00:00Z",
    food_type: "중형견용 일반사료",
    recommended_g: 70,
  },
  {
    id: "dog-7",
    name: "7번 개체",
    breed_code: "SHIHTZU",
    breed_name_ko: "시츄",
    weight_kg: 6.1,
    status: "active",
    created_at: "2026-02-28T10:00:00Z",
    food_type: "처방식",
    recommended_g: 60,
    vet_note: "비만 관리 중. 권장량 5g 감량.",
  },
];

export const devices: Device[] = [
  {
    id: "dev-1",
    name: "급식기 1번",
    location: "메인 견사 A",
    last_seen: "2026-03-27T22:33:00Z",
    status: "online",
    food_remaining_pct: 78,
  },
  {
    id: "dev-2",
    name: "급식기 2번",
    location: "메인 견사 B",
    last_seen: "2026-03-27T22:33:00Z",
    status: "online",
    food_remaining_pct: 45,
  },
];

export const feedings: FeedingRecord[] = [
  {
    id: "fr-1",
    dog_id: "dog-1",
    dog_name: "1번 개체",
    breed_name_ko: "몰티즈",
    device_id: "dev-1",
    device_name: "급식기 1번",
    scheduled_at: "2026-03-27T09:32:00Z",
    dispensed_at: "2026-03-27T09:32:15Z",
    dispensed_g: 60,
    consumed_g: 60,
    status: "completed",
    confidence: 0.942,
  },
  {
    id: "fr-2",
    dog_id: null,
    dog_name: "미등록",
    breed_name_ko: "-",
    device_id: "dev-2",
    device_name: "급식기 2번",
    scheduled_at: "2026-03-27T09:28:00Z",
    dispensed_g: 0,
    consumed_g: 0,
    status: "blocked",
  },
  {
    id: "fr-3",
    dog_id: "dog-5",
    dog_name: "5번 개체",
    breed_name_ko: "시츄",
    device_id: "dev-1",
    device_name: "급식기 1번",
    scheduled_at: "2026-03-27T09:15:00Z",
    dispensed_g: 55,
    consumed_g: 45,
    status: "incomplete",
  },
  {
    id: "fr-4",
    dog_id: "dog-3",
    dog_name: "3번 개체",
    breed_name_ko: "포메라니안",
    device_id: "dev-1",
    device_name: "급식기 1번",
    scheduled_at: "2026-03-27T09:02:00Z",
    dispensed_g: 50,
    consumed_g: 48,
    status: "completed",
  },
  {
    id: "fr-5",
    dog_id: "dog-4",
    dog_name: "4번 개체",
    breed_name_ko: "비숑프리제",
    device_id: "dev-2",
    device_name: "급식기 2번",
    scheduled_at: "2026-03-27T08:45:00Z",
    dispensed_g: 55,
    consumed_g: 55,
    status: "completed",
  },
  {
    id: "fr-6",
    dog_id: "dog-6",
    dog_name: "6번 개체",
    breed_name_ko: "믹스견",
    device_id: "dev-1",
    device_name: "급식기 1번",
    scheduled_at: "2026-03-27T08:30:00Z",
    dispensed_g: 70,
    consumed_g: 70,
    status: "completed",
  },
  {
    id: "fr-7",
    dog_id: "dog-7",
    dog_name: "7번 개체",
    breed_name_ko: "시츄",
    device_id: "dev-2",
    device_name: "급식기 2번",
    scheduled_at: "2026-03-27T08:12:00Z",
    dispensed_g: 60,
    consumed_g: 38,
    status: "incomplete",
  },
];

export const alerts: AppAlert[] = [
  {
    id: "al-1",
    dog_id: null,
    type: "unregistered_access",
    title: "미등록 개체 접근",
    message: "급식기 2번에 미등록 개체가 접근하여 배식이 자동 중단되었습니다.",
    severity: "danger",
    created_at: "2026-03-27T09:28:00Z",
    resolved_at: null,
  },
  {
    id: "al-2",
    dog_id: "dog-2",
    type: "missed_feeding",
    title: "2번 개체 미섭취",
    message: "2번 개체(푸들)가 오전 급식 시간에 섭취하지 않았습니다.",
    severity: "warn",
    created_at: "2026-03-27T10:00:00Z",
    resolved_at: null,
  },
  {
    id: "al-3",
    dog_id: "dog-7",
    type: "abnormal_intake",
    title: "7번 섭취량 감소",
    message: "7번 개체(시츄)의 최근 3일 평균 섭취량이 30% 감소했습니다.",
    severity: "warn",
    created_at: "2026-03-27T10:15:00Z",
    resolved_at: null,
  },
  {
    id: "al-4",
    dog_id: null,
    type: "new_dog",
    title: "신규 개체 등록",
    message: "새로운 개체가 자동 등록되었습니다. (품종: 비숑프리제)",
    severity: "info",
    created_at: "2026-03-26T14:22:00Z",
    resolved_at: "2026-03-26T14:22:00Z",
  },
  {
    id: "al-5",
    dog_id: null,
    type: "system",
    title: "시스템 업데이트",
    message: "YOLO v8 모델이 최신 버전으로 업데이트되었습니다.",
    severity: "info",
    created_at: "2026-03-26T02:00:00Z",
    resolved_at: "2026-03-26T02:00:00Z",
  },
  {
    id: "al-6",
    dog_id: "dog-3",
    type: "vet_change",
    title: "수의사 급여량 변경",
    message: "김수의사가 3번 개체의 급여량을 55g에서 50g으로 조정했습니다.",
    severity: "info",
    created_at: "2026-03-26T11:40:00Z",
    resolved_at: "2026-03-26T11:40:00Z",
  },
];

// 7일 섭취량 시계열 (1번 개체 기준)
export const intake7d = [
  { day: "월", consumed_g: 55, recommended_g: 60 },
  { day: "화", consumed_g: 60, recommended_g: 60 },
  { day: "수", consumed_g: 58, recommended_g: 60 },
  { day: "목", consumed_g: 60, recommended_g: 60 },
  { day: "금", consumed_g: 60, recommended_g: 60 },
  { day: "토", consumed_g: 60, recommended_g: 60 },
  { day: "일", consumed_g: 0, recommended_g: 60 },
];

// 30일 섭취량 (수의사 페이지)
export const intake30d = Array.from({ length: 30 }, (_, i) => ({
  day: `${i + 1}`,
  consumed_g: 50 + Math.round(Math.sin(i / 3) * 8 + (Math.random() * 6 - 3)),
}));
